export const HANDLE_PLAY_PAUSE = 'HANDLE_PLAY_PAUSE';
export const HANDLE_PROGRESS_PRESS = 'HANDLE_PROGRESS_PRESS';
export const HANDLE_STATUS = 'HANDLE_STATUS';
export const HANDLE_QUALITY = 'HANDLE_QUALITY';
export const HANDLE_READY = 'HANDLE_READY';
export const HANDLE_ERROR = 'HANDLE_ERROR';
export const HANDLE_PROGRESS = 'HANDLE_PROGRESS';
export const ADD_RECIPE = 'ADD_RECIPE';